version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - CSV_FILE=data.csv
      - TARGET_COLUMN=target
    volumes:
      - ./path/to/local:/path/to/local
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
